/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.ucsd.nlp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import edu.ucsd.nlp.model.SKOSCollaborationEntry;
import edu.ucsd.nlp.model.SKOSCollaborationEntryModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SKOSCollaborationEntry service. Represents a row in the &quot;SKOS_CollaborationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link edu.ucsd.nlp.model.SKOSCollaborationEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SKOSCollaborationEntryImpl}.
 * </p>
 *
 * @author http://nlp-app.ucsd.edu
 * @see SKOSCollaborationEntryImpl
 * @see edu.ucsd.nlp.model.SKOSCollaborationEntry
 * @see edu.ucsd.nlp.model.SKOSCollaborationEntryModel
 * @generated
 */
public class SKOSCollaborationEntryModelImpl extends BaseModelImpl<SKOSCollaborationEntry>
	implements SKOSCollaborationEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s k o s collaboration entry model instance should use the {@link edu.ucsd.nlp.model.SKOSCollaborationEntry} interface instead.
	 */
	public static final String TABLE_NAME = "SKOS_CollaborationEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "skosFileId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "updateType", Types.VARCHAR },
			{ "schemeURI", Types.VARCHAR },
			{ "conceptURI", Types.VARCHAR },
			{ "value", Types.VARCHAR },
			{ "type_", Types.VARCHAR },
			{ "type2", Types.VARCHAR },
			{ "lang", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SKOS_CollaborationEntry (id_ LONG not null primary key,skosFileId LONG,userId LONG,updateType VARCHAR(75) null,schemeURI STRING null,conceptURI STRING null,value VARCHAR(75) null,type_ VARCHAR(75) null,type2 VARCHAR(75) null,lang VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SKOS_CollaborationEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY skosCollaborationEntry.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SKOS_CollaborationEntry.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.edu.ucsd.nlp.model.SKOSCollaborationEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.edu.ucsd.nlp.model.SKOSCollaborationEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.edu.ucsd.nlp.model.SKOSCollaborationEntry"),
			true);
	public static long SKOSFILEID_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.edu.ucsd.nlp.model.SKOSCollaborationEntry"));

	public SKOSCollaborationEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SKOSCollaborationEntry.class;
	}

	@Override
	public String getModelClassName() {
		return SKOSCollaborationEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("skosFileId", getSkosFileId());
		attributes.put("userId", getUserId());
		attributes.put("updateType", getUpdateType());
		attributes.put("schemeURI", getSchemeURI());
		attributes.put("conceptURI", getConceptURI());
		attributes.put("value", getValue());
		attributes.put("type", getType());
		attributes.put("type2", getType2());
		attributes.put("lang", getLang());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long skosFileId = (Long)attributes.get("skosFileId");

		if (skosFileId != null) {
			setSkosFileId(skosFileId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String updateType = (String)attributes.get("updateType");

		if (updateType != null) {
			setUpdateType(updateType);
		}

		String schemeURI = (String)attributes.get("schemeURI");

		if (schemeURI != null) {
			setSchemeURI(schemeURI);
		}

		String conceptURI = (String)attributes.get("conceptURI");

		if (conceptURI != null) {
			setConceptURI(conceptURI);
		}

		String value = (String)attributes.get("value");

		if (value != null) {
			setValue(value);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String type2 = (String)attributes.get("type2");

		if (type2 != null) {
			setType2(type2);
		}

		String lang = (String)attributes.get("lang");

		if (lang != null) {
			setLang(lang);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getSkosFileId() {
		return _skosFileId;
	}

	@Override
	public void setSkosFileId(long skosFileId) {
		_columnBitmask |= SKOSFILEID_COLUMN_BITMASK;

		if (!_setOriginalSkosFileId) {
			_setOriginalSkosFileId = true;

			_originalSkosFileId = _skosFileId;
		}

		_skosFileId = skosFileId;
	}

	public long getOriginalSkosFileId() {
		return _originalSkosFileId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUpdateType() {
		if (_updateType == null) {
			return StringPool.BLANK;
		}
		else {
			return _updateType;
		}
	}

	@Override
	public void setUpdateType(String updateType) {
		_updateType = updateType;
	}

	@Override
	public String getSchemeURI() {
		if (_schemeURI == null) {
			return StringPool.BLANK;
		}
		else {
			return _schemeURI;
		}
	}

	@Override
	public void setSchemeURI(String schemeURI) {
		_schemeURI = schemeURI;
	}

	@Override
	public String getConceptURI() {
		if (_conceptURI == null) {
			return StringPool.BLANK;
		}
		else {
			return _conceptURI;
		}
	}

	@Override
	public void setConceptURI(String conceptURI) {
		_conceptURI = conceptURI;
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return StringPool.BLANK;
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public String getType2() {
		if (_type2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _type2;
		}
	}

	@Override
	public void setType2(String type2) {
		_type2 = type2;
	}

	@Override
	public String getLang() {
		if (_lang == null) {
			return StringPool.BLANK;
		}
		else {
			return _lang;
		}
	}

	@Override
	public void setLang(String lang) {
		_lang = lang;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SKOSCollaborationEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SKOSCollaborationEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SKOSCollaborationEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SKOSCollaborationEntryImpl skosCollaborationEntryImpl = new SKOSCollaborationEntryImpl();

		skosCollaborationEntryImpl.setId(getId());
		skosCollaborationEntryImpl.setSkosFileId(getSkosFileId());
		skosCollaborationEntryImpl.setUserId(getUserId());
		skosCollaborationEntryImpl.setUpdateType(getUpdateType());
		skosCollaborationEntryImpl.setSchemeURI(getSchemeURI());
		skosCollaborationEntryImpl.setConceptURI(getConceptURI());
		skosCollaborationEntryImpl.setValue(getValue());
		skosCollaborationEntryImpl.setType(getType());
		skosCollaborationEntryImpl.setType2(getType2());
		skosCollaborationEntryImpl.setLang(getLang());

		skosCollaborationEntryImpl.resetOriginalValues();

		return skosCollaborationEntryImpl;
	}

	@Override
	public int compareTo(SKOSCollaborationEntry skosCollaborationEntry) {
		long primaryKey = skosCollaborationEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SKOSCollaborationEntry)) {
			return false;
		}

		SKOSCollaborationEntry skosCollaborationEntry = (SKOSCollaborationEntry)obj;

		long primaryKey = skosCollaborationEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SKOSCollaborationEntryModelImpl skosCollaborationEntryModelImpl = this;

		skosCollaborationEntryModelImpl._originalSkosFileId = skosCollaborationEntryModelImpl._skosFileId;

		skosCollaborationEntryModelImpl._setOriginalSkosFileId = false;

		skosCollaborationEntryModelImpl._originalUserId = skosCollaborationEntryModelImpl._userId;

		skosCollaborationEntryModelImpl._setOriginalUserId = false;

		skosCollaborationEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SKOSCollaborationEntry> toCacheModel() {
		SKOSCollaborationEntryCacheModel skosCollaborationEntryCacheModel = new SKOSCollaborationEntryCacheModel();

		skosCollaborationEntryCacheModel.id = getId();

		skosCollaborationEntryCacheModel.skosFileId = getSkosFileId();

		skosCollaborationEntryCacheModel.userId = getUserId();

		skosCollaborationEntryCacheModel.updateType = getUpdateType();

		String updateType = skosCollaborationEntryCacheModel.updateType;

		if ((updateType != null) && (updateType.length() == 0)) {
			skosCollaborationEntryCacheModel.updateType = null;
		}

		skosCollaborationEntryCacheModel.schemeURI = getSchemeURI();

		String schemeURI = skosCollaborationEntryCacheModel.schemeURI;

		if ((schemeURI != null) && (schemeURI.length() == 0)) {
			skosCollaborationEntryCacheModel.schemeURI = null;
		}

		skosCollaborationEntryCacheModel.conceptURI = getConceptURI();

		String conceptURI = skosCollaborationEntryCacheModel.conceptURI;

		if ((conceptURI != null) && (conceptURI.length() == 0)) {
			skosCollaborationEntryCacheModel.conceptURI = null;
		}

		skosCollaborationEntryCacheModel.value = getValue();

		String value = skosCollaborationEntryCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			skosCollaborationEntryCacheModel.value = null;
		}

		skosCollaborationEntryCacheModel.type = getType();

		String type = skosCollaborationEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			skosCollaborationEntryCacheModel.type = null;
		}

		skosCollaborationEntryCacheModel.type2 = getType2();

		String type2 = skosCollaborationEntryCacheModel.type2;

		if ((type2 != null) && (type2.length() == 0)) {
			skosCollaborationEntryCacheModel.type2 = null;
		}

		skosCollaborationEntryCacheModel.lang = getLang();

		String lang = skosCollaborationEntryCacheModel.lang;

		if ((lang != null) && (lang.length() == 0)) {
			skosCollaborationEntryCacheModel.lang = null;
		}

		return skosCollaborationEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", skosFileId=");
		sb.append(getSkosFileId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", updateType=");
		sb.append(getUpdateType());
		sb.append(", schemeURI=");
		sb.append(getSchemeURI());
		sb.append(", conceptURI=");
		sb.append(getConceptURI());
		sb.append(", value=");
		sb.append(getValue());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", type2=");
		sb.append(getType2());
		sb.append(", lang=");
		sb.append(getLang());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("edu.ucsd.nlp.model.SKOSCollaborationEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>skosFileId</column-name><column-value><![CDATA[");
		sb.append(getSkosFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updateType</column-name><column-value><![CDATA[");
		sb.append(getUpdateType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>schemeURI</column-name><column-value><![CDATA[");
		sb.append(getSchemeURI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>conceptURI</column-name><column-value><![CDATA[");
		sb.append(getConceptURI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type2</column-name><column-value><![CDATA[");
		sb.append(getType2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lang</column-name><column-value><![CDATA[");
		sb.append(getLang());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SKOSCollaborationEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SKOSCollaborationEntry.class
		};
	private long _id;
	private long _skosFileId;
	private long _originalSkosFileId;
	private boolean _setOriginalSkosFileId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _updateType;
	private String _schemeURI;
	private String _conceptURI;
	private String _value;
	private String _type;
	private String _type2;
	private String _lang;
	private long _columnBitmask;
	private SKOSCollaborationEntry _escapedModel;
}