/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.ucsd.nlp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ObjectHistory service. Represents a row in the &quot;SKOS_ObjectHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.ucsd.nlp.model.impl.ObjectHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.ucsd.nlp.model.impl.ObjectHistoryImpl}.
 * </p>
 *
 * @author http://nlp-app.ucsd.edu
 * @see ObjectHistory
 * @see edu.ucsd.nlp.model.impl.ObjectHistoryImpl
 * @see edu.ucsd.nlp.model.impl.ObjectHistoryModelImpl
 * @generated
 */
public interface ObjectHistoryModel extends BaseModel<ObjectHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a object history model instance should use the {@link ObjectHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this object history.
	 *
	 * @return the primary key of this object history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this object history.
	 *
	 * @param primaryKey the primary key of this object history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this object history.
	 *
	 * @return the ID of this object history
	 */
	public long getId();

	/**
	 * Sets the ID of this object history.
	 *
	 * @param id the ID of this object history
	 */
	public void setId(long id);

	/**
	 * Returns the skos file ID of this object history.
	 *
	 * @return the skos file ID of this object history
	 */
	public long getSkosFileId();

	/**
	 * Sets the skos file ID of this object history.
	 *
	 * @param skosFileId the skos file ID of this object history
	 */
	public void setSkosFileId(long skosFileId);

	/**
	 * Returns the user ID of this object history.
	 *
	 * @return the user ID of this object history
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this object history.
	 *
	 * @param userId the user ID of this object history
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this object history.
	 *
	 * @return the user uuid of this object history
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this object history.
	 *
	 * @param userUuid the user uuid of this object history
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the recorded of this object history.
	 *
	 * @return the recorded of this object history
	 */
	public Date getRecorded();

	/**
	 * Sets the recorded of this object history.
	 *
	 * @param recorded the recorded of this object history
	 */
	public void setRecorded(Date recorded);

	/**
	 * Returns the type of this object history.
	 *
	 * @return the type of this object history
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this object history.
	 *
	 * @param type the type of this object history
	 */
	public void setType(String type);

	/**
	 * Returns the scheme u r i of this object history.
	 *
	 * @return the scheme u r i of this object history
	 */
	@AutoEscape
	public String getSchemeURI();

	/**
	 * Sets the scheme u r i of this object history.
	 *
	 * @param schemeURI the scheme u r i of this object history
	 */
	public void setSchemeURI(String schemeURI);

	/**
	 * Returns the concept u r i of this object history.
	 *
	 * @return the concept u r i of this object history
	 */
	@AutoEscape
	public String getConceptURI();

	/**
	 * Sets the concept u r i of this object history.
	 *
	 * @param conceptURI the concept u r i of this object history
	 */
	public void setConceptURI(String conceptURI);

	/**
	 * Returns the value of this object history.
	 *
	 * @return the value of this object history
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this object history.
	 *
	 * @param value the value of this object history
	 */
	public void setValue(String value);

	/**
	 * Returns the object type of this object history.
	 *
	 * @return the object type of this object history
	 */
	@AutoEscape
	public String getObjectType();

	/**
	 * Sets the object type of this object history.
	 *
	 * @param objectType the object type of this object history
	 */
	public void setObjectType(String objectType);

	/**
	 * Returns the object type2 of this object history.
	 *
	 * @return the object type2 of this object history
	 */
	@AutoEscape
	public String getObjectType2();

	/**
	 * Sets the object type2 of this object history.
	 *
	 * @param objectType2 the object type2 of this object history
	 */
	public void setObjectType2(String objectType2);

	/**
	 * Returns the lang of this object history.
	 *
	 * @return the lang of this object history
	 */
	@AutoEscape
	public String getLang();

	/**
	 * Sets the lang of this object history.
	 *
	 * @param lang the lang of this object history
	 */
	public void setLang(String lang);

	/**
	 * Returns the details of this object history.
	 *
	 * @return the details of this object history
	 */
	@AutoEscape
	public String getDetails();

	/**
	 * Sets the details of this object history.
	 *
	 * @param details the details of this object history
	 */
	public void setDetails(String details);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ObjectHistory objectHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ObjectHistory> toCacheModel();

	@Override
	public ObjectHistory toEscapedModel();

	@Override
	public ObjectHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}