/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.ucsd.nlp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SKOSFile service. Represents a row in the &quot;SKOS_File&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.ucsd.nlp.model.impl.SKOSFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.ucsd.nlp.model.impl.SKOSFileImpl}.
 * </p>
 *
 * @author http://nlp-app.ucsd.edu
 * @see SKOSFile
 * @see edu.ucsd.nlp.model.impl.SKOSFileImpl
 * @see edu.ucsd.nlp.model.impl.SKOSFileModelImpl
 * @generated
 */
public interface SKOSFileModel extends BaseModel<SKOSFile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s k o s file model instance should use the {@link SKOSFile} interface instead.
	 */

	/**
	 * Returns the primary key of this s k o s file.
	 *
	 * @return the primary key of this s k o s file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s k o s file.
	 *
	 * @param primaryKey the primary key of this s k o s file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the skos file ID of this s k o s file.
	 *
	 * @return the skos file ID of this s k o s file
	 */
	public long getSkosFileId();

	/**
	 * Sets the skos file ID of this s k o s file.
	 *
	 * @param skosFileId the skos file ID of this s k o s file
	 */
	public void setSkosFileId(long skosFileId);

	/**
	 * Returns the user ID of this s k o s file.
	 *
	 * @return the user ID of this s k o s file
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this s k o s file.
	 *
	 * @param userId the user ID of this s k o s file
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s k o s file.
	 *
	 * @return the user uuid of this s k o s file
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s k o s file.
	 *
	 * @param userUuid the user uuid of this s k o s file
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the parent ID of this s k o s file.
	 *
	 * @return the parent ID of this s k o s file
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this s k o s file.
	 *
	 * @param parentId the parent ID of this s k o s file
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the last modified by of this s k o s file.
	 *
	 * @return the last modified by of this s k o s file
	 */
	public long getLastModifiedBy();

	/**
	 * Sets the last modified by of this s k o s file.
	 *
	 * @param lastModifiedBy the last modified by of this s k o s file
	 */
	public void setLastModifiedBy(long lastModifiedBy);

	/**
	 * Returns the created of this s k o s file.
	 *
	 * @return the created of this s k o s file
	 */
	public Date getCreated();

	/**
	 * Sets the created of this s k o s file.
	 *
	 * @param created the created of this s k o s file
	 */
	public void setCreated(Date created);

	/**
	 * Returns the modified of this s k o s file.
	 *
	 * @return the modified of this s k o s file
	 */
	public Date getModified();

	/**
	 * Sets the modified of this s k o s file.
	 *
	 * @param modified the modified of this s k o s file
	 */
	public void setModified(Date modified);

	/**
	 * Returns the name of this s k o s file.
	 *
	 * @return the name of this s k o s file
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this s k o s file.
	 *
	 * @param name the name of this s k o s file
	 */
	public void setName(String name);

	/**
	 * Returns the contents of this s k o s file.
	 *
	 * @return the contents of this s k o s file
	 */
	@AutoEscape
	public String getContents();

	/**
	 * Sets the contents of this s k o s file.
	 *
	 * @param contents the contents of this s k o s file
	 */
	public void setContents(String contents);

	/**
	 * Returns the version of this s k o s file.
	 *
	 * @return the version of this s k o s file
	 */
	public double getVersion();

	/**
	 * Sets the version of this s k o s file.
	 *
	 * @param version the version of this s k o s file
	 */
	public void setVersion(double version);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SKOSFile skosFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SKOSFile> toCacheModel();

	@Override
	public SKOSFile toEscapedModel();

	@Override
	public SKOSFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}