/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.ucsd.nlp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SKOSCollaborationEntry service. Represents a row in the &quot;SKOS_CollaborationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.ucsd.nlp.model.impl.SKOSCollaborationEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.ucsd.nlp.model.impl.SKOSCollaborationEntryImpl}.
 * </p>
 *
 * @author http://nlp-app.ucsd.edu
 * @see SKOSCollaborationEntry
 * @see edu.ucsd.nlp.model.impl.SKOSCollaborationEntryImpl
 * @see edu.ucsd.nlp.model.impl.SKOSCollaborationEntryModelImpl
 * @generated
 */
public interface SKOSCollaborationEntryModel extends BaseModel<SKOSCollaborationEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s k o s collaboration entry model instance should use the {@link SKOSCollaborationEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this s k o s collaboration entry.
	 *
	 * @return the primary key of this s k o s collaboration entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s k o s collaboration entry.
	 *
	 * @param primaryKey the primary key of this s k o s collaboration entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s k o s collaboration entry.
	 *
	 * @return the ID of this s k o s collaboration entry
	 */
	public long getId();

	/**
	 * Sets the ID of this s k o s collaboration entry.
	 *
	 * @param id the ID of this s k o s collaboration entry
	 */
	public void setId(long id);

	/**
	 * Returns the skos file ID of this s k o s collaboration entry.
	 *
	 * @return the skos file ID of this s k o s collaboration entry
	 */
	public long getSkosFileId();

	/**
	 * Sets the skos file ID of this s k o s collaboration entry.
	 *
	 * @param skosFileId the skos file ID of this s k o s collaboration entry
	 */
	public void setSkosFileId(long skosFileId);

	/**
	 * Returns the user ID of this s k o s collaboration entry.
	 *
	 * @return the user ID of this s k o s collaboration entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this s k o s collaboration entry.
	 *
	 * @param userId the user ID of this s k o s collaboration entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s k o s collaboration entry.
	 *
	 * @return the user uuid of this s k o s collaboration entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s k o s collaboration entry.
	 *
	 * @param userUuid the user uuid of this s k o s collaboration entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the update type of this s k o s collaboration entry.
	 *
	 * @return the update type of this s k o s collaboration entry
	 */
	@AutoEscape
	public String getUpdateType();

	/**
	 * Sets the update type of this s k o s collaboration entry.
	 *
	 * @param updateType the update type of this s k o s collaboration entry
	 */
	public void setUpdateType(String updateType);

	/**
	 * Returns the scheme u r i of this s k o s collaboration entry.
	 *
	 * @return the scheme u r i of this s k o s collaboration entry
	 */
	@AutoEscape
	public String getSchemeURI();

	/**
	 * Sets the scheme u r i of this s k o s collaboration entry.
	 *
	 * @param schemeURI the scheme u r i of this s k o s collaboration entry
	 */
	public void setSchemeURI(String schemeURI);

	/**
	 * Returns the concept u r i of this s k o s collaboration entry.
	 *
	 * @return the concept u r i of this s k o s collaboration entry
	 */
	@AutoEscape
	public String getConceptURI();

	/**
	 * Sets the concept u r i of this s k o s collaboration entry.
	 *
	 * @param conceptURI the concept u r i of this s k o s collaboration entry
	 */
	public void setConceptURI(String conceptURI);

	/**
	 * Returns the value of this s k o s collaboration entry.
	 *
	 * @return the value of this s k o s collaboration entry
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this s k o s collaboration entry.
	 *
	 * @param value the value of this s k o s collaboration entry
	 */
	public void setValue(String value);

	/**
	 * Returns the type of this s k o s collaboration entry.
	 *
	 * @return the type of this s k o s collaboration entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this s k o s collaboration entry.
	 *
	 * @param type the type of this s k o s collaboration entry
	 */
	public void setType(String type);

	/**
	 * Returns the type2 of this s k o s collaboration entry.
	 *
	 * @return the type2 of this s k o s collaboration entry
	 */
	@AutoEscape
	public String getType2();

	/**
	 * Sets the type2 of this s k o s collaboration entry.
	 *
	 * @param type2 the type2 of this s k o s collaboration entry
	 */
	public void setType2(String type2);

	/**
	 * Returns the lang of this s k o s collaboration entry.
	 *
	 * @return the lang of this s k o s collaboration entry
	 */
	@AutoEscape
	public String getLang();

	/**
	 * Sets the lang of this s k o s collaboration entry.
	 *
	 * @param lang the lang of this s k o s collaboration entry
	 */
	public void setLang(String lang);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SKOSCollaborationEntry skosCollaborationEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SKOSCollaborationEntry> toCacheModel();

	@Override
	public SKOSCollaborationEntry toEscapedModel();

	@Override
	public SKOSCollaborationEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}